-- AlterTable
ALTER TABLE "Employer" ADD COLUMN     "coverPositionX" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "coverPositionY" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "coverZoom" INTEGER NOT NULL DEFAULT 100;
